version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=productivity
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend/flask
    environment:
      - DATABASE_URL=postgresql+psycopg2://app:app@db:5432/productivity
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
      - CORS_ALLOW_ORIGINS=http://localhost:5173
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:5000
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  db_data:
